"""empty message

Revision ID: b7a7d0e94ebf
Revises: 8d06ee8249c7
Create Date: 2024-11-05 13:08:55.685327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a7d0e94ebf'
down_revision = '8d06ee8249c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
